### ISSUE TITLE
Can't get correct result on windows platform

### ISSUE THREAD

**Issue by jnoylinc** [gishi523/coarse-to-fine-patchmatch#1]
hi,I build a project to run this code on vs2013, and I use the opencv3.1 and opencv_contrip310.
when I choose a debug version, errors happened
Opencv Error: Assertion failed <<unsigned>i1 < <unsugned>size.p[1]> in cv::Mat::ptr
when I choose a release version, I get a flow image, but it is not right!
Anyone encountered same problem?
Please offer some help~ Thx~

**Comment by gishi523** [comment]
HI,
Thank you for your information.
I'll check.
Dones the error occur in any images?

**Comment by jnoylinc** [comment]
yes,thanks for your help.

**Comment by gishi523** [comment]
HI,

I've not test with VS2013 + OpenCV3.1 yet,
but I could run correctly with at least following environments.
- VS2013 + OpenCV3.2
- VS2015 + OpenCV3.3

Regards,

**Comment by gishi523** [comment]
Hi, I could see the error with OpenCV3.1, and I found bug in daisy implementation.

In function ni_get_histogram (ni means no interpolation), [this line](https://github.com/opencv/opencv_contrib/blob/3.1.0/modules/xfeatures2d/src/daisy.cpp#L583) is wrong.

The correct is
```cpp
const float* hptr = hcube->ptr<float>(0, y, x);
```

So, the solution is any of the following
- Update OpenCV version to 3.2 or higher.
- Set interpolation flag true. Interpolation mode doesn't seem to have the issue.
- Correct source code as described above, and rebuild.

Regards,

**Comment by jnoylinc** [comment]
thanks for your help, you make the world better!
Regards,
